# Generated by Django 5.0.6 on 2024-05-24 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Financas',
            fields=[
                ('id_meta', models.AutoField(primary_key=True, serialize=False)),
                ('nome_meta', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=300)),
                ('valor_total', models.FloatField()),
                ('valor_mensal', models.FloatField()),
                ('parcelas_totais', models.IntegerField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'financas',
            },
        ),
    ]
